final products = [
  {
    'id': '0',
    'title': "Men's Air Jordan Black",
    'price': 44.52,
    'sizes': [8, 9, 10, 11],
    'merk': 'Adidas',
    'imageUrl': 'assets/images/shoes1.jpg',
  },
  {
    'id': '1',
    'title': "Men's Air Jordan Red",
    'price': 47.52,
    'sizes': [8, 9, 10, 11],
    'merk': 'Nike',
    'imageUrl': 'assets/images/shoes2.jpeg',
  },
  {
    'id': '2',
    'title': "Men's Air Jordan Green",
    'price': 45.52,
    'sizes': [8, 9, 10, 11],
    'merk': 'Bata',
    'imageUrl': 'assets/images/shoes3.jpeg',
  },
  {
    'id': '3',
    'title': "Men's Air Jordan Blue",
    'price': 41.52,
    'sizes': [8, 9, 10, 11],
    'merk': 'Adidas',
    'imageUrl': 'assets/images/shoes4.jpeg',
  },
  {
    'id': '4',
    'title': "Men's Air Jordan Cream",
    'price': 49.52,
    'sizes': [8, 9, 10, 11],
    'merk': 'Nike',
    'imageUrl': 'assets/images/shoes5.webp',
  },
];
